baseURL = "/"
title = "じゃがびぃのサイト"
languageCode = "ja"
defaultContentLanguage = "ja"
hasCJKLanguage = true
theme = "hugo-blog-awesome"
canonifyURLs = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
ignoreErrors = ["additional-script-loading-error"]

[frontmatter]
lastmod = [":git", ":fileModTime", ":default"]

[services.googleAnalytics]
id = "G-3FGTMKYNHZ"

[outputs]
home = ["HTML", "RSS"]

[permalinks]
posts = "/posts/:slug/"
weekly = "/weekly/:slug/"

[related]
includeNewer = true
threshold = 60
toLower = false
[[related.indices]]
name = "tags"
weight = 100
[[related.indices]]
name = "categories"
weight = 200

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
