title = "じゃがびぃのサイト"
languageCode = "ja"
languageName = "Japanese"
weight = 1
[params.author]
name = "じゃがびぃ"
image = "/img/icon_j.jpg"
headline = "スマホとかハード系のものが好きです"
bio = "なんか色々触ってます"
links = [
	{ twitter = "https://x.com/Jyaga_bee" },
	{ discord = "https://discord.com/users/831536477758423040" },
	{ github = "https://github.com/Jyagabee" },
	{ threads = "https://www.threads.net/@jyagabee_" },
	{ telegram = "https://t.me/Jyagabee" },
	{ misskey = "https://mk.tenpest-moon.uk/@Jyagabee" },
]
[params]
desplayName = "JA"
isoCode = "ja"
dateFormat = "2006/01/02 15:04"
  [params.article]
    showTableOfContents = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	  startLevel = 1 
	  endLevel = 5