title = "じゃがびぃのサイト"
languageCode = "ja"
languageName = "日本語"
[params.author]
name = "じゃがびぃ"
image = "/img/icon.jpg"
headline = "スマホとかハード系のものが好きです"
bio = "最近はc言語で色々やろうと考えています。考えるだけです。"
links = [
	{ twitter = "https://x.com/Jyaga_bee" }
	{ misskey = "https://mk.tenpest-moon.uk/@Jyagabee" }
]
[params]
desplayName = "JA"
isoCode = "ja"
dateFormat = "2006/01/02 15:04"
