[[socialIcons]]
name = "twitter"
url = "https://twitter.com/Jyaga_bee"

[[socialIcons]]
name = "github"
url = "https://github.com/Jyagabee"

[[socialIcons]]
name = "Rss"
url = "/index.xml"

[browserconfig]
TileColor = "#2d89ef"
