# PaperMod テーマの設定

# 基本設定
env = "production"
description = "じゃがびぃのサイト - スマホとかハード系のものが好きです"
author = "じゃがびぃ"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
comments = false
images = ["/img/icon_j.jpg"]

# ホームページ設定
[homeInfoParams]
Title = "じゃがびぃのサイトへようこそ 🥔"
Content = "スマホとかハード系のものが好きです"

# プロフィール設定
[profileMode]
enabled = false

# ソーシャルアイコン
[[socialIcons]]
name = "twitter"
title = "Twitter"
url = "https://twitter.com/Jyaga_bee"

[[socialIcons]]
name = "github"
title = "GitHub"
url = "https://github.com/Jyagabee"

# 検索設定
[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

# ラベル
[label]
text = "じゃがびぃのサイト"
icon = "/img/icon_j.jpg"
iconHeight = 35

# カバー画像設定
[cover]
linkFullImages = true
hidden = false
hiddenInList = false
hiddenInSingle = false
responsiveImages = true

# Google Analytics
[analytics.google]
SiteVerificationTag = "G-3FGTMKYNHZ"
