[[socialIcons]]
name = "twitter"
url = "https://twitter.com/Jyaga_bee"

[[socialIcons]]
name = "github"
url = "https://github.com/Jyagabee"

[[socialIcons]]
name = "misskey"
url = "https://mk.tenpest-moon.uk/@Jyagabee"

[[socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/jyagabee.bsky.social" 

[[socialIcons]]
name = "Rss"
url = "/index.xml"

[browserconfig]
TileColor = "#2d89ef"
